### PR TITLE
i prefer to see and read leading dots. i disabled this style so we ca…

### PR DESCRIPTION
**Pull request by sjahandideh**
…n have both

### CODE REVIEW

**Comment by gogogarrett** [comment]
Can you show some examples of before / after - and some reasons why you believe this rule is on/off better?

**Comment by sjahandideh** [comment]
Sure. look at this link. Both ways are correct and widely used.
https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains

**Comment by gogogarrett** [comment]
imo - it's not really a compelling enough reason to change the style PLUS all the code we already have that conforms to the old rules - happy to hear others thoughts though

**Comment by sjahandideh** [comment]
that's why i didn't change trailing to leading, just disabled it, so we won't need to change existing code. i wouldn't mind seeing both styles in the code. but i'm very much used to leading dots myself. what does everyone else think?

**Comment by mfeckie** [comment]
My opinion is leading dot, but I've followed what was the agree convention.

**Comment by Bockit** [comment]
I'm more JS than ruby but the idea of trailing dots is very foreign to me, I hadn't seen it till I came here.

Since it's disabling rather than changing, this wouldn't force a rewrite of all the existing code

**Comment by corinnebrady** [comment]
I prefer leading dot so I would be happy with disabling this

**Comment by JamesFerguson** [comment]
Reading the conversation, this seems like a pretty solid pro for trailing dots - paste the following into a console:

```
%w{a b c}.
  map(&:upcase).
  map(&:ord)
# => [65, 66, 67] 
```

vs

```
%w{a b c}
  .map(&:upcase)
  .map(&:ord)
# SyntaxError: (irb):71: syntax error, unexpected '.'
# ... 30 lines of stack trace
```

i.e. whenever you want to cut and paste trailing dot code from your editor to run it in the console, it just works. If you try the same with leading dot code it explodes and you need to remove the newlines or copy and paste in pieces.

Personally, I was in the habit of leading dots too, but the above is enough to move me to the trailing dots camp.

Likewise, though less common, you can get away with comments between lines with trailing dots:

```
%w{a b c}.
  # we really need to upcase
  map(&:upcase).
  map(&:ord)
# fine
```

vs

```
    %w{a b c}
      # we really need to upcase
      .map(&:upcase)
      .map(&:ord)
# syntax error, unexpected '.'
```

More generally, I think consistency is valuable. I think it's so valuable I'd rather us be consistent about a suboptimal alternative than inconsistent. IMHO more often than not variation/freedom is a net loss. Variability is a visual and mental distraction, it tempts you to rewrite code to your preferred style which leads to commit log noise and it encourages arguments about which style is better which are mostly bike-shedding.

I would go so far as to say that the only time letting individuals choose is the best option is when the team is nearly perfectly evenly divided on a rule and it's going to waste more time trying get a consensus than would be lost be allowing free choice. e.g. this was the case when we talked about whether to allow use of single quotes.

**Comment by Owenhorner** [comment]
I have no preference reading trailing or leading dots. I don't see how disabling it will have any major impact on the quality of our code. :+1: if everyone is on board

**Comment by sjahandideh** [comment]
@JamesFerguson i love your thorough explanation. thanks for that. Your first example is a great explanation of why someone would prefer trailing dots in my openion. however, the second one is a very good reason why we shouldn't use it. because something like this may happen:

``` ruby
%w{a b c}.
  # we really need to upcase
  # we really need to upcase
  # we really need to upcase
  # we really need to upcase
  # we really need to upcase
  map(&:upcase).
  map(&:ord)
# fine
```

Regarding consistency and freedom, again I'll be very happy to have that discussion sometime. I don't think we should force everybody the exact same set of rules besides the normal conventions. I believe too much restriction kills creativity and passion and develops a sense of irresponsibility. As programmers, I think we should see our code as a piece of art and we should mind having our name on a piece of code that we don't believe is right just for the sake of consistency.

**Comment by kunzmann** [comment]
Well done @JamesFerguson on reading the conversation of pros & cons...I agree that the irb/pry & commenting side of things are compelling even though I prefer the look of leading dots. I don't think anyone is arguing for the ability to put comments in the middle of these chains @sjahandideh - but I think the ability to quickly comment one section of a chain could be useful:

``` ruby
%w{a b c}.
  #map(&:upcase).
  map(&:ord)
```

:point_up: in the context of debugging or whatever, not to be committed that way.

All that said, I'm still not particularly against merging this PR though.

**Comment by JamesFerguson** [comment]
That's a great example @kunzmann, I hadn't thought of that. That actually makes me want trailing dots even more. Either that or I'll end up looking for a regexp/vim plugin to auto-trailing-dot every file on open.

**Comment by geoffroh** [comment]
There should be a rule against full-line comments in the middle of method chains, imagine a leading dot like this:

```
a = %w{a b c}
      # yep you got an array there
      # nothing to see here
      # move along
      #
      # nice array you have there
      # it would be a shame if someone were to..
      .map(&:upcase)
      .map(&:ord)
```

Commenting on the same line would be OK:

```
.map(&:upcase) # we really need to upcase
```

Anyway, back to the bikeshedding, I don't mind either way and probably wouldn't even notice if you switched from one to the other in the same method chain, so :+1: on the PR for me.

**Comment by sjahandideh** [comment]
@kunzmann nope, not sold on that. if you are commenting that code, you better delete it

**Comment by JamesFerguson** [comment]
@sjahandideh the point is, iff the code is trailing-dot to begin with, you can comment a line and rerun specs or whatever. If it's leading dot and you comment a line (just locally for debug purposes) and run it, it will fail.

I think we're all agreed we don't commit commented code.

But to me that's two cases where trailing dots are a practical benefit, and none where leading dots are anything but what we're used to. I'd argue trailing dots are objectively easier to work with.

**Comment by bedrock-adam** [comment]
I'm indifferent about either styles, each have their own merits and disadvantages as discussed.

**Comment by sjahandideh** [comment]
@JamesFerguson well, i think we all made our points. i see your point of view about trailing dots and it makes sense but i'm not sold on the comments. it gives the ability to have comments inside the statement but it also gives the ability to create long commented statements which are difficult to read. also, i find it easier to read a statement that starts with a dot. it visually gives me the expectation that this code is a piece that tails to another one.
But thankfully this PR is not about choosing trailing vs leading. it's about being able to pick whichever we like :smile:

**Comment by JamesFerguson** [comment]
> it also gives the ability to create long commented statements which are difficult to read.

There are lots of ways to put comments in places you shouldn't, preventing people doing that is rubocop's job. 

But then as you said, your proposal won't stop people using trailing dots so it won't prevent this anyway, it just means we don't get the benefits of trailing dots most of the time either.

> it visually gives me the expectation that this code is a piece that tails to another one.

That's what I would've said too. But, really, indentation does that just fine.

The one benefit of leading dots I can see is that it makes it really visually obvious if you leave off a dot. And that was worth something in languages like VB or PHP that have a "keep running at all costs" mentality that sometimes makes it hard to track down basic syntax errors. But that's not that big a deal in ruby. If you leave off a dot by accident you're going to hear about it from tests very quickly and it'll be easy to sort out.

> But thankfully this PR is not about choosing trailing vs leading. it's about being able to pick whichever we like :smile:

"being able to pick whichever we like" is talking in terms of the code we _write_. But we [spend far more time reading (and interacting with) existing code than we do writing new code](http://blog.codinghorror.com/when-understanding-means-rewriting/). Being able to write trailing dots is not what I care about, I want trailing dots to be there when I come to debug existing code - because of the benefits mentioned above. This PR means more often than not they won't be there for any given piece of code.

**Comment by MarcusHoile** [comment]
having to reformat code, to paste into a console would be pretty frustrating especially if you are trying to debug CS tickets.

**Pull request closed without merging**
