### PR TITLE
Prefer single quotes for string literals

### PR DESCRIPTION
**Pull request by novemberkilo**
Defering to the author of rubocop and what I think(?!) is consensus within the team - https://github.com/bbatsov/ruby-style-guide#consistent-string-literals

### CODE REVIEW

**Comment by gogogarrett** [comment]
I'm a double string guy myself - but I'm happy to conform if everyone wants single quotes.

**Comment by stuart** [comment]
:+1: I do tend to double quotes myself too, but don't mind if there is a consensus.

( In real languages a single quoted string is a list of characters which is not the same thing as a double quoted string which is a binary. :P )

**Comment by timkoopmans** [comment]
in case you were wondering ...

http://stackoverflow.com/questions/1836467/is-there-a-performance-gain-in-using-single-quotes-vs-double-quotes-in-ruby

> Summary: no speed difference; this great collaborative ruby style guide recommends being consistent. I now use 'string' unless interpolation is needed (option A in the guide) and like it, but you will typically see more code with "string".

**Comment by JamesFerguson** [comment]
I don't see any need to be consistent about this. Let people do whatever they like. We'll all cope.

**Comment by novemberkilo** [comment]
Following @JamesFerguson we could also just completely drop any stylistic reference to quotes - to each their own. If this is a non-issue and we don't have consensus, let's just not care about this? I like the idea of consistency across a team but don't care so much about this issue. 

What say we to that?

**Comment by kunzmann** [comment]
:+1: to not caring

**Comment by gogogarrett** [comment]
:+1: to each their own

**Comment by JamesFerguson** [comment]
:shipit:

**Pull request merged**
